# Generated by Django 4.1.11 on 2023-10-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=100, null=True)),
                ('stu_name', models.CharField(max_length=100, null=True)),
                ('stu_room_num', models.IntegerField(default=0, null=True)),
                ('stu_seat_num', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
