# Generated by Django 4.1.11 on 2023-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=100, null=True)),
                ('stu_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=100, null=True)),
                ('stu_name', models.CharField(max_length=100, null=True)),
                ('stu_room_num', models.IntegerField(default=0, null=True)),
                ('stu_seat_num', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100, null=True)),
                ('class_teacher', models.CharField(max_length=100, null=True)),
                ('class_year', models.CharField(max_length=100, null=True)),
                ('class_season', models.CharField(max_length=100, null=True)),
                ('student_list', models.ManyToManyField(to='myapp.student')),
            ],
        ),
    ]
