# Generated by Django 4.1.11 on 2023-11-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='is_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='is_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('er_id', models.AutoField(primary_key=True, serialize=False)),
                ('er_name', models.CharField(max_length=100, null=True)),
                ('er_student_list', models.ManyToManyField(to='myapp.studenttable')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=100, null=True)),
                ('exam_time', models.CharField(max_length=100, null=True)),
                ('exam_room_list', models.ManyToManyField(to='myapp.examroom')),
                ('join_class_list', models.ManyToManyField(to='myapp.studentclass')),
            ],
        ),
    ]
