# Generated by Django 4.1.11 on 2023-11-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_studenttable_is_register_studenttable_is_submit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_id', models.IntegerField(default=0, null=True)),
                ('static_password', models.CharField(max_length=100, null=True)),
                ('static_cookie', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
