# Generated by Django 4.1.11 on 2023-11-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_staticdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoomSeatCase',
            fields=[
                ('ersc_id', models.AutoField(primary_key=True, serialize=False)),
                ('ersc_seat_num', models.IntegerField(default=0, null=True)),
                ('ersc_x', models.IntegerField(default=0, null=True)),
                ('ersc_y', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='examroom',
            name='er_case_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='ExamRoomCase',
            fields=[
                ('erc_id', models.AutoField(primary_key=True, serialize=False)),
                ('erc_name', models.CharField(max_length=100, null=True)),
                ('erc_x_length', models.IntegerField(default=0, null=True)),
                ('erc_y_length', models.IntegerField(default=0, null=True)),
                ('erc_seats', models.ManyToManyField(to='myapp.examroomseatcase')),
            ],
        ),
    ]
