# Generated by Django 4.1.11 on 2023-11-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_examroomseatcase_examroom_er_case_id_examroomcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
