# Generated by Django 4.1.11 on 2023-11-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticdata',
            name='static_lpvt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticdata',
            name='static_lvt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
